### ISSUE TITLE
building on Window 11 MinGE64?

### ISSUE THREAD

**Issue by lonnietc** [jerrinsg/go-pmem#26]
Hello,

I am trying to build go-pmem on a Windows 11 using MSYS2 (Mingw64) for which I am running Go 1.18.

```
lonni@DESKTOP10 MINGW64 ~/go-pmem/test/src
$ ./make.bat
ERROR: Cannot find C:/msys64/mingw64/bin/go\bin\go.exe
Set GOROOT_BOOTSTRAP to a working Go tree >= Go 1.4.
```

I have tried using "set" and "export" to set the GOROOT_BOOTSTRAP variable, but I still get the same result.

Can you please advise?

**Comment by jerrinsg** [comment]
Hello,

We have tested go-pmem only on Linux. Are you able to compile upstream Go (https://github.com/golang/go) on your machine? This looks like an issue of missing tools/dependencies and not go-pmem specific. See if the instructions on https://go.dev/doc/install/source help, otherwise I'd recommend asking on one of the Go help channels.

Thanks,
Jerrin
